# Generated by Django 4.0.3 on 2022-03-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creator',
            new_name='creater',
        ),
    ]
