# Generated by Django 4.0.3 on 2022-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_creator_job_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position_name',
            field=models.CharField(max_length=100),
        ),
    ]
