# Generated by Django 4.0.3 on 2022-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('expected_salary', models.IntegerField()),
                ('relocation', models.BooleanField(default=False)),
            ],
        ),
    ]
